version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: legallens
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  clamav:
    image: clamav/clamav:latest
    ports:
      - "3310:3310"
    volumes:
      - clamav-data:/var/lib/clamav
    healthcheck:
      test: ["CMD", "clamdscan", "--ping", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ../
      dockerfile: apps/api/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres@postgres:5432/legallens?schema=public"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - ../apps/api:/app
      - ../packages:/packages
      - /app/node_modules
      - /packages/database/node_modules
    command: sh -c "cd /packages/database && npx prisma generate && cd /app && npm run dev"

volumes:
  postgres-data:
  redis-data:
  minio-data:
  clamav-data: